baseurl: /blog
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
author: Emmanuel Jacyna
title: BaKGL
description: Docs about the BaKGL project
collections:
  content:
    output: true
header_pages:
  - index.md
  - content/index.md
