remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
author: Emmanuel Jacyna
title: BaKGL
description: Some interesting things learned while remaking Betrayal at Krondor
collections:
  content:
    output: true
header_pages:
  - index.md
  - content/index.md
